### ISSUE TITLE
Incorrect link on airbnb.io

### ISSUE THREAD

**Issue by dferber90** [airbnb/aerosolve#13]
If you go to http://airbnb.io/projects/aerosolve/ and click on the big red GitHub button, you are actually redirected to the airpal repository. I know this issue is not related to aerosolve itself, but I didn't know where to tell you best.

**Comment by phillmv** [comment]
dangit, beat me to it!

**Comment by hectorgon** [comment]
Thanks for finding the bug! It should be fixed now
