### ISSUE TITLE
Incorrect jar name

### ISSUE THREAD

**Issue by roncemer** [airbnb/aerosolve#21]
In demo/income_prediction/job_runner.sh, the version number for the income prediction jar file is old.  As a result, there is a ClassNotFoundException when trying to find the JobRunner class.

Existing:
build/libs/income_prediction-0.1.3-all.jar \

Should be:
build/libs/income_prediction-0.1.6-all.jar \

Please apply this change and commit to the git repo.

Thanks!

**Comment by deerzq** [comment]
The issue has been fixed. Thanks!
