### ISSUE TITLE
missing FeatureVector.java

### ISSUE THREAD

**Issue by boluoyu** [airbnb/aerosolve#22]
missing FeatureVector.java,then project can't build

**Comment by hectorgon** [comment]
You need to install the thrift compiler in your path somewhere
https://thrift.apache.org/
If you are on mac use `brew install thrift`

If you are just running the demos you don't have to build the core or training libs just the demo directories as those grab the already generated java files using thrift.

**Comment by boluoyu** [comment]
sorry to reply so late，when I installed  thrift then project build success . thank you very much.
