### ISSUE TITLE
Can't found file： com.airbnb.aerosolve.core.FeatureVector

### ISSUE THREAD

**Issue by LvHengshan** [airbnb/aerosolve#248]
Hello:
In file： FeatureVectorGen line3，4 can‘t found example and featureVector, is this an error?
Thanks.

import com.airbnb.aerosolve.core.Example;
import com.airbnb.aerosolve.core.FeatureVector;

**Comment by LvHengshan** [comment]
should install Thrift first

**Comment by huangmx201712** [comment]
I had the same problem, and I installed it. Can you help me?
