### ISSUE TITLE
combineContextAndItems(Example examples)

### ISSUE THREAD

**Issue by randombishop** [airbnb/aerosolve#75]
While trying to use aerosolve for kaggle airbnb competition, I noticed in com.airbnb.aerosolve.core.transforms.Transformer.java
that only string features are being copied from context to examples.
Is this behavior coded on purpose ?
In general, is the differentiation between context and item features only for memory optimization or does it impact the algorithms ranking task ?
Thanks in advance for any advices to help.

**Comment by hectorgon** [comment]
Oops sorry that was not intended. It is mainly for bandwidth optimization when scoring a single context with multiple items (e.g. a single user profile and hundreds of items they might like). For now please use just the repeated example list to store your features.

**Comment by hectorgon** [comment]
Looks like a pretty easy fix. @christhetree - could you please take a stab at this issue

**Comment by christhetree** [comment]
Cool, I'll take a look.

**Comment by randombishop** [comment]
Great, thanks a lot guys
